#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 04, 2017 08:15:11 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import emotions_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    emotions_support.set_Tk_var()
    top = Cameras (root)
    emotions_support.init(root, top)
    root.mainloop()

w = None
def create_Cameras(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    emotions_support.set_Tk_var()
    top = Cameras (w)
    emotions_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Cameras():
    global w
    w.destroy()
    w = None


class Cameras:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("1254x846+336+86")
        top.title("Cameras")



        self.PanelControl = LabelFrame(top)
        self.PanelControl.place(relx=0.73, rely=0.04, relheight=0.93
                , relwidth=0.26)
        self.PanelControl.configure(relief=GROOVE)
        self.PanelControl.configure(width=330)

        self.btnStart = Button(self.PanelControl)
        self.btnStart.place(relx=0.27, rely=0.08, height=56, width=147)
        self.btnStart.configure(activebackground="#d9d9d9")
        self.btnStart.configure(text='''Start''')
        self.btnStart.configure(width=147)

        self.ckEmotions = Checkbutton(self.PanelControl)
        self.ckEmotions.place(relx=0.52, rely=0.17, relheight=0.04
                , relwidth=0.25)
        self.ckEmotions.configure(activebackground="#d9d9d9")
        self.ckEmotions.configure(justify=LEFT)
        self.ckEmotions.configure(text='''Emotions''')
        self.ckEmotions.configure(variable=emotions_support.che44)
        self.ckEmotions.configure(width=81)

        self.ckFaces = Checkbutton(self.PanelControl)
        self.ckFaces.place(relx=0.27, rely=0.17, relheight=0.04, relwidth=0.18)
        self.ckFaces.configure(activebackground="#d9d9d9")
        self.ckFaces.configure(justify=LEFT)
        self.ckFaces.configure(text='''Faces''')
        self.ckFaces.configure(variable=emotions_support.che44)
        self.ckFaces.configure(width=61)

        self.btnAdd = Button(self.PanelControl)
        self.btnAdd.place(relx=0.27, rely=0.27, height=56, width=147)
        self.btnAdd.configure(activebackground="#d9d9d9")
        self.btnAdd.configure(text='''Add Person''')

        self.btnTrain = Button(self.PanelControl)
        self.btnTrain.place(relx=0.27, rely=0.4, height=56, width=147)
        self.btnTrain.configure(activebackground="#d9d9d9")
        self.btnTrain.configure(text='''Train''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.02, rely=0.04, height=738, width=866)
        self.Label1.configure(background="#b1d9db")
        self.Label1.configure(width=866)






if __name__ == '__main__':
    vp_start_gui()







# "python.linting.pylintArgs": [  "--errors-only",
#                                     "--disable=C0103",
#                                     "--extension-pkg-whitelist=cv2"],
#     "extensions.ignoreRecommendations": true,
#     "window.zoomLevel": 0